// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nojhjjcnfnchijcxvglf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5vamhqamNuZm5jaGlqY3h2Z2xmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4MzEwNjUsImV4cCI6MjA3MjQwNzA2NX0.nD1rIHA2iHxlvRjNKVu9iXvX-pX3ZW0jK9MYCEVo4SI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});