// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://afrvcloymsyshljixixr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFmcnZjbG95bXN5c2hsaml4aXhyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4OTE1NTcsImV4cCI6MjA1ODQ2NzU1N30.clHLcYWN0CT8sV1NzBSp705e0GdduguLi0Uma1dZPa0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);