
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
// Removed Database type import because src/integrations/supabase/types.ts is empty and causes "never" types
// import type { Database } from './types';

const SUPABASE_URL = "https://cfsqxwxstvcfwefhqvjt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNmc3F4d3hzdHZjZndlZmhxdmp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2NTY2ODYsImV4cCI6MjA3MDIzMjY4Nn0.V-obmReB3ANDg6uxIVbsrFTYVAaSCoBMD--CvbBJ6e4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Remove the generic <Database> to avoid "never" types when the Database definition is empty
export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
